### ISSUE TITLE
installing sybil on ubuntu 22

### ISSUE THREAD

**Issue by hariszaf** [SysBioChalmers/sybil#7]
Hello there, 

I would like to install `sybil` on Ubuntu 22 with an R `4.1.2`?

Is than an option ? 

Thanks a lot in advance

**Comment by mihai-sysbio** [comment]
Hi @hariszaf! As `sybil` is not on CRAN for now, one has to install it from GitHub. [Here is a guide on how to do this](https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html). The commands you would need to run are:

```
library(devtools)
install_github("SysBioChalmers/sybil")

**Comment by hariszaf** [comment]
HI @mihai-sysbio ! Thanks for the reply. 

I followed your instructions and `sybil` is now installed both on `R.4.1.2` and `R.4.2.2`. 

Thanks a lot! :tada:
