### ISSUE TITLE
install on ubuntu 22

### ISSUE THREAD

**Issue by hariszaf** [SysBioChalmers/sybil#8]
Hello, 

i am trying to install `sybil` in Ubuntu 22 with an R version `4.1.2`. 

I have tried multiple ways but i end up with errors. 

Is it possible to install `sybil` in this set up? 
If yes, could you share how to do so ? 

Many thanks in advance!

**Comment by mihai-sysbio** [comment]
I don't see why not it wouldn't be possible - it would be great if you could try and let us know.

**Comment by mihai-sysbio** [comment]
In the meantime I got my hands on an Ubuntu 22.04 machine, and installing sybil went as smoothly as expected.

@hariszaf could you try again, following the [updated installation instructions in the Readme](https://github.com/SysBioChalmers/sybil#installation)?

**Comment by hariszaf** [comment]
Hi @mihai-sysbio 
Thanks for mentioning! 
I now installed `sybil` on Ubuntu22 and in R version 4.1.0 just fine! 
I guess the issue can be considered resolved. :tada:

**Comment by mihai-sysbio** [comment]
That's great to hear, thanks for confirming @hariszaf
